apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgresql-psl.fullname" . }}-pv
  labels:
    app: {{ include "postgresql-psl.fullname" . }}
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.dbconfig.postgresDBDataDir }}