apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql-psl.fullname" . }}-pvc
spec:
  storageClassName: manual
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
          storage: 1Gi
  selector:
    matchLabels:
      app: {{ include "postgresql-psl.fullname" . }}
