apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-psl.fullname" . }}
  labels:
    {{- include "postgresql-psl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "postgresql-psl.selectorLabels" . | nindent 4 }}
